<template>
  <v-container>
    <WorkflowHeader title="Species Hypotheses (MOTU)"></WorkflowHeader>
    <p class="mb-3">
      A MOTU (Molecular Operational Taxonomic Unit) is a grouping of individuals by sequence
      similarity, at a potentially finer level than the species.
    </p>
    <p class="mb-3">
      In a MOTU analysis, sequences in a dataset are grouped together, resulting in a set of MOTUs.
      Each sequence is assigned to one MOTU, which is identified by a number. The set of MOTUs and
      corresponding sequence assignments define a dataset.
    </p>

    <DetailWorkflow :nodes="nodes" :edges="edges" v-bind="$attrs" />
    <GiscusWrapper term="Species hypotheses"></GiscusWrapper>
  </v-container>
</template>

<script setup lang="ts">
import type { Edge } from '@vue-flow/core'
import type { Node } from '@/components/DetailWorkflow.vue'

import { ref } from 'vue'
import { defaultHandles } from '@/components/MultipleHandleNode.vue'
import DetailWorkflow from '@/components/DetailWorkflow.vue'
import WorkflowHeader from '@/components/WorkflowHeader.vue'
import GiscusWrapper from '@/components/GiscusWrapper.vue'

const nodeDefinitions: Node[] = [
  {
    id: 'sequencing',
    type: 'custom',
    label: 'Sequencing',
    position: { x: 0, y: 0 },
    data: {
      handles: defaultHandles(['bot']),
      icon: 'fa-dna',
      target: 'sequencing'
    }
  },
  {
    id: 'ext-sequences',
    type: 'custom',
    label: 'External sequences',
    position: { x: 300, y: 0 },
    data: {
      handles: defaultHandles(['bot']),
      icon: 'fa-dna',
      target: 'external-sequence'
    }
  },
  {
    id: 'motu',
    type: 'custom',
    label: 'MOTU',
    position: { x: 150, y: 200 },
    data: {
      handles: defaultHandles(['top', 'right']),
      icon: 'fa-tag',
      items: [
        {
          title: 'Number',
          content: { text: 'A numeric identifier for the MOTU, unique within one dataset ' }
        },
        {
          title: 'Delimitation method',
          content: {
            text: [
              'The clustering method used to obtain a MOTU',
              'e.g. Poisson Tree Process, Generalized Mixed Yule Coalescent'
            ]
          }
        }
      ]
    }
  },
  {
    id: 'dataset',
    type: 'custom',
    label: 'MOTU Dataset',
    position: { x: 600, y: 200 },
    data: {
      icon: 'fa-grip',
      items: [
        { title: 'Label' },
        { title: 'Date' },
        { title: 'Generated by', appendIcon: 'fas fa-users' },
        { title: 'Published in', appendIcon: 'fas fa-newspaper' }
      ],
      handles: defaultHandles(['left'])
    }
  }
]

const nodes = ref(nodeDefinitions)

const edges: Edge[] = [
  {
    id: 'seq-motu',
    source: 'sequencing',
    target: 'motu',
    sourceHandle: 'bot',
    targetHandle: 'top',
    animated: true
  },
  {
    id: 'ext-seq-motu',
    source: 'ext-sequences',
    target: 'motu',
    sourceHandle: 'bot',
    targetHandle: 'top',
    animated: true
  },
  {
    id: 'motu-dataset',
    source: 'motu',
    target: 'dataset',
    sourceHandle: 'right',
    targetHandle: 'left'
  }
]
</script>
