<template>
  <v-container>
    <h1 class="text-h4">Species Hypotheses</h1>
    <v-divider class="my-3"></v-divider>
    <p class="mb-3">
      Sample collection is the starting point of the research workflow. A sampling operation is done
      on a site, whose coordinates and location are kept track of, as well as some descriptive
      variables such as the habitat type (e.g. subterranean freshwater, river). It targets one or
      several taxonomic groups.
    </p>
    <p class="mb-3">
      A sampling operation provides one or several bundles of
      <a href="" @click.prevent="$emit('goToWorkflow', 'biomat')">biological material</a>.
    </p>

    <DetailWorkflow :nodes="nodes" :edges="edges" v-bind="$attrs" />
  </v-container>
</template>

<script setup lang="ts">
import type { Edge } from '@vue-flow/core'
import type { Node } from '@/components/DetailWorkflow.vue'

import { ref } from 'vue'
import { Position } from '@vue-flow/core'
import { defaultHandles } from '@/components/MultipleHandleNode.vue'
import DetailWorkflow from '@/components/DetailWorkflow.vue'

const nodeDefinitions: Node[] = [
  {
    id: 'sequencing',
    type: 'custom',
    label: 'Sequencing',
    position: { x: 0, y: 0 },
    data: {
      handles: defaultHandles(['bot']),
      icon: 'fa-dna',
      target: 'sequencing'
    }
  },
  {
    id: 'motu',
    type: 'custom',
    label: 'MOTU',
    position: { x: 0, y: 200 },
    data: {
      handles: defaultHandles(['top', 'right']),
      icon: 'fa-tag',
      items: [{ title: 'Number' }, { title: 'Delimitation method' }]
    }
  },
  {
    id: 'dataset',
    type: 'custom',
    label: 'MOTU Dataset',
    position: { x: 300, y: 200 },
    data: {
      icon: 'fa-grip',
      items: [{ title: 'Label' }, { title: 'Date' }, { title: 'Generated by' }],
      handles: defaultHandles(['left'])
    }
  }
]

const nodes = ref(nodeDefinitions)

const edges: Edge[] = [
  {
    id: 'seq-motu',
    source: 'sequencing',
    target: 'motu',
    sourceHandle: 'bot',
    targetHandle: 'top',
    animated: true
  },
  {
    id: 'motu-dataset',
    source: 'motu',
    target: 'dataset',
    sourceHandle: 'right',
    targetHandle: 'left'
  }
]
</script>
